### ISSUE TITLE
Cannot invoke method clientCredentials() on null object

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/openapi-plugin#3]
I am seeing following error when trying to use the plugin.

2022-04-07 16:24:03.752 ERROR --- [nio-8080-exec-4] o.g.web.errors.GrailsExceptionResolver   : NullPointerException occurred when processing request: [GET] /openapi/openapi.json
Cannot invoke method clientCredentials() on null object. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at au.org.ala.web.Pac4jHttpServletRequestWrapperFilter.internalFilter(Pac4jHttpServletRequestWrapperFilter.groovy:46)
	at org.pac4j.core.config.AbstractConfigFilter.doFilter(AbstractConfigFilter.java:70)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: Cannot invoke method clientCredentials() on null object
	at au.org.ala.plugins.openapi.OpenApiService$_getOpenApi_closure1.doCall(OpenApiService.groovy:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at au.org.ala.plugins.openapi.OpenApiService.getOpenApi(OpenApiService.groovy:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at au.org.ala.plugins.openapi.OpenApiService.openApiJsonString(OpenApiService.groovy:171)
	at au.org.ala.plugins.openapi.OpenApiController$_openapi_closure1$_closure2.doCall(OpenApiController.groovy:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.grails.plugins.web.api.MimeTypesApiSupport.getResponseForFormat(MimeTypesApiSupport.groovy:142)
	at org.grails.plugins.web.api.MimeTypesApiSupport.withFormatInternal(MimeTypesApiSupport.groovy:57)
	at org.grails.plugins.web.api.MimeTypesApiSupport.withFormat(MimeTypesApiSupport.groovy:44)
	at grails.artefact.Controller$Trait$Helper.withFormat(Controller.groovy:94)
	at au.org.ala.plugins.openapi.OpenApiController.openapi(OpenApiController.groovy:23)
	... 17 common frames omitted

**Comment by yasima-csiro** [comment]
This issue has been fixed.
